### ISSUE TITLE
Refactor configuration system: Remove unnecessary config options and simplify user experience

### ISSUE THREAD

**Issue by sonesuke** [sonesuke/oboyu#149]
# Configuration Refactoring: Simplify and Streamline

## Problem Statement

The current configuration system has grown complex with many unnecessary options that provide minimal value to users while increasing cognitive overhead. Based on codebase analysis, many configuration options are either:

- Hard-coded values that cannot actually be changed
- Over-engineered parameters that 99% of users never need to modify
- Academic/expert-level settings that should be internal defaults
- Redundant with environment variables or auto-detection

## Goals

1. **Simplify user experience** by removing ~60% of current config options
2. **Keep only essential configurations** that users actually need to modify
3. **Improve maintainability** by reducing configuration surface area
4. **Update documentation** to reflect the simplified configuration

### Keep Only Essential Configuration

**Basic Configuration (keep only these):**
```yaml
# Essential settings users actually need
indexer:
  db_path: "~/.oboyu/index.db"  # Most important user setting
  chunk_size: 1024              # Document processing
  chunk_overlap: 256            # Document processing
  embedding_model: "cl-nagoya/ruri-v3-30m"  # Core model choice
  use_reranker: true            # Quality vs speed tradeoff

crawler:
  include_patterns: ["*.txt", "*.md", "*.py"]  # What to index
  exclude_patterns: ["*/node_modules/*"]       # What to skip

query:
  default_mode: "hybrid"        # Search behavior
  top_k: 5                     # Results count
```

#### 1. Hard-coded Values (remove from config)
- `crawler.max_file_size` (hard-coded to 10MB)
- `crawler.follow_symlinks` (hard-coded to false)

#### 2. Over-engineered Parameters (make internal defaults)
- `reranker_batch_size`, `reranker_max_length`, `reranker_device`
- `bm25_k1`, `bm25_b`, `bm25_min_token_length`
- `ef_construction`, `ef_search`, `m` (HNSW parameters)
- `batch_size`, `max_workers` (auto-optimize based on system)

#### 3. UI/Display Settings (remove from core config)
- `snippet_length`, `highlight_matches`, `show_scores`
- These should be runtime options only

#### 4. Rarely Used Options
- `language_filter` (runtime option only)
- `reranker_threshold` (defaults work for 99% of cases)
- `change_detection_strategy` (smart default is sufficient)

#### 5. Environment Variable Duplicates
- `onnx_cache_dir` (use XDG standard paths)
- Paths that can be set via `OBOYU_*` environment variables

#### Phase 1: Code Changes
- [ ] Create new simplified configuration dataclasses
- [ ] Add backward compatibility layer for existing configs
- [ ] Implement auto-optimization for removed parameters
- [ ] Add deprecation warnings for removed config options

#### Phase 2: Configuration Migration
- [ ] Add configuration migration utility
- [ ] Validate that removed options have sensible internal defaults
- [ ] Ensure environment variable handling works properly

#### Phase 3: Documentation Updates
- [ ] Update `docs/configuration.md` with simplified examples
- [ ] Revise CLI documentation to reflect changes
- [ ] Update all example configurations throughout docs
- [ ] Add migration guide for existing users

#### Phase 4: Testing
- [ ] Ensure backward compatibility with existing config files
- [ ] Test that defaults work well across different use cases
- [ ] Validate that advanced users can still access expert settings if needed

## Benefits

1. **Better UX**: New users won't be overwhelmed by 30+ configuration options
2. **Easier Maintenance**: Fewer config options means fewer edge cases and bugs
3. **Self-Optimizing**: System can auto-tune parameters based on usage patterns
4. **Cleaner Docs**: Documentation becomes much more approachable

## Backward Compatibility

- Existing config files will continue to work with deprecation warnings
- Migration script will help users update to new format
- Expert users can still access advanced settings via environment variables or code

### Code Files
- `src/oboyu/config/` - All configuration classes
- `src/oboyu/cli/` - Command line argument parsing
- `src/oboyu/common/config.py` - Core config handling

### Documentation Files
- `docs/configuration.md` - Complete rewrite with simplified examples
- `docs/cli.md` - Update command examples
- `docs/indexer.md` - Remove references to removed config options
- `docs/mcp_server.md` - Update configuration examples
- All other docs with configuration examples

## Success Criteria

- [ ] Configuration options reduced from ~30 to ~8-10 essential options
- [ ] All existing functionality preserved with sensible defaults
- [ ] Documentation is clear and concise
- [ ] Existing users can migrate smoothly
- [ ] New users can get started with minimal configuration

## Related Issues

This addresses user feedback about configuration complexity and aligns with the project's goal of simplicity while maintaining power-user capabilities.
