### ISSUE TITLE
Optimize GitHub workflows: Remove pre-merge redundancy and improve docs build validation

### ISSUE THREAD

**Issue by sonesuke** [sonesuke/oboyu#205]
## Problem Analysis

After reviewing the current workflow setup, several inefficiencies have been identified:

### Current Issues

1. **Pre-merge workflow redundancy**
   - The `pre-merge.yml` workflow contains checks that overlap with other workflows
   - Content and timing redundancies are causing unnecessary CI execution time
   - This workflow may not be providing unique value

2. **Insufficient documentation build validation timing**
   - Documentation build checks only happen at merge time, which is too late
   - Need to validate documentation builds when PRs are created to catch issues early
   - Current timing leads to potential merge-blocking issues that could be caught earlier

### Proposed Solution

**Restructure workflows for efficiency and better validation:**

#### 1. Replace `pre-merge.yml` with `pr-validation.yml`
```yaml
name: PR Validation
on:
  pull_request:
    branches: [main]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      # Code quality checks (lint, type check, tests)
      # Consolidate only essential checks from existing pre-merge workflow
  
  docs-build-validation:
    runs-on: ubuntu-latest
    steps:
      # Documentation build verification
      # Early detection of documentation issues at PR stage
```

#### 2. Enhance post-merge workflow
```yaml
name: Post-merge Actions
on:
  push:
    branches: [main]

jobs:
  deploy-docs:
    # Actual documentation deployment
    # Final verification and deployment after merge
```

#### 3. Keep release workflows unchanged
- Maintain existing `release.yml`, `prerelease.yml`, `test-pypi.yml`

### Implementation Plan

1. **Remove redundant workflow**
   - Delete `pre-merge.yml` 
   - Consolidate essential checks into new PR validation workflow

2. **Split documentation validation into two stages**
   - **PR stage**: Build validation only (fast feedback)
   - **Post-merge**: Actual deployment

3. **Performance optimization**
   - Optimize parallel job execution
   - Improve caching efficiency
   - Implement fail-fast strategies to reduce wasted execution time

### Expected Benefits

- **Reduced execution time**: Eliminate duplicate checks
- **Early issue detection**: Documentation validation at PR stage
- **Clear separation of concerns**: Each stage has a distinct purpose
- **Improved maintainability**: Simpler, more understandable workflows

### Acceptance Criteria

- [ ] Remove `pre-merge.yml` workflow
- [ ] Create new `pr-validation.yml` with consolidated essential checks
- [ ] Add documentation build validation to PR workflow
- [ ] Ensure post-merge documentation deployment continues working
- [ ] Verify overall CI execution time is reduced
- [ ] Test that documentation issues are caught at PR stage

This optimization will improve development efficiency and make the CI/CD pipeline more effective.
