### ISSUE TITLE
Integrate enhanced E2E tests with GitHub Actions CI/CD

### ISSUE THREAD

**Issue by sonesuke** [sonesuke/oboyu#233]
# Integrate enhanced E2E tests with GitHub Actions CI/CD

## Summary
Integrate the enhanced ttyd + Playwright E2E testing framework with GitHub Actions CI/CD pipeline to enable automated visual verification, cross-browser testing, and continuous quality assurance for every commit and pull request.

## Background
Following the completion of the enhanced E2E framework (#231) and full migration (#232), this final phase focuses on:
- **CI/CD Integration**: Seamless GitHub Actions pipeline integration
- **Cross-browser Testing**: Automated testing across multiple browsers
- **Visual Regression Detection**: Automated screenshot comparison in CI
- **Performance Optimization**: Efficient CI resource utilization
- **Reporting Integration**: Automated test reports and PR comments

## Prerequisites
- ✅ Issue #231 completed (ttyd + Playwright integration)
- ✅ Issue #232 completed (Full E2E test migration)
- ✅ Enhanced E2E framework fully functional locally
- ✅ Visual baselines established for regression detection

## Goals
- [ ] Create GitHub Actions workflows for enhanced E2E testing
- [ ] Implement cross-browser testing matrix (Chromium, Firefox)
- [ ] Add automated visual regression detection
- [ ] Enable cost-optimized testing modes
- [ ] Set up automated reporting and PR integration
- [ ] Optimize CI performance and resource usage

### Phase 1: Basic CI Integration
1. **GitHub Actions Workflow Setup**
   ```yaml
   # .github/workflows/e2e-enhanced.yml
   name: Enhanced E2E Tests (ttyd + Playwright)
   
   on:
     push:
       branches: [ main, develop ]
     pull_request:
       branches: [ main ]
   ```

2. **Environment Configuration**
   - Ubuntu runner with ttyd and Xvfb
   - Playwright browser installation
   - Python environment setup with uv

### Phase 2: Cross-browser Testing Matrix
1. **Multi-browser Support**
   - Chromium-based testing (primary)
   - Firefox testing (compatibility)
   - WebKit testing (optional, for comprehensive coverage)

2. **Parallel Execution Strategy**
   - Independent browser test jobs
   - Efficient resource allocation
   - Failure isolation and reporting

### Phase 3: Visual Regression & Reporting
1. **Visual Regression Detection**
   - Baseline screenshot comparison
   - Automated difference highlighting
   - Regression threshold configuration

2. **Enhanced Reporting**
   - PR comment integration
   - Artifact management (screenshots, reports)
   - Performance metrics tracking

### Main E2E Workflow
```yaml
# .github/workflows/e2e-enhanced.yml
name: Enhanced E2E Tests (ttyd + Playwright)

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  e2e-enhanced:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    strategy:
      fail-fast: false
      matrix:
        browser: [chromium, firefox]
        test-suite: [cli, indexing, search, mcp]
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ttyd xvfb
        
    - name: Set up uv
      uses: astral-sh/setup-uv@v3
      
    - name: Install Python dependencies
      run: |
        uv sync --all-extras
        uv run playwright install ${{ matrix.browser }} --with-deps
        
    - name: Create test directories
      run: |
        mkdir -p screenshots
        mkdir -p test-reports
        mkdir -p visual-diffs
        
    - name: Run enhanced E2E tests
      env:
        ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        BROWSER_TYPE: ${{ matrix.browser }}
        DISPLAY: :99
        CI_MODE: true
      run: |
        # Start Xvfb for headless browser display
        Xvfb :99 -screen 0 1920x1080x24 &
        sleep 2
        
        # Run specific test suite
        uv run python e2e/run_enhanced_tests.py \
          --test ${{ matrix.test-suite }} \
          --browser ${{ matrix.browser }} \
          --ci-mode \
          --report test-reports/e2e-${{ matrix.browser }}-${{ matrix.test-suite }}.md
          
    - name: Visual regression detection
      if: github.event_name == 'pull_request'
      run: |
        uv run python e2e/visual_regression_check.py \
          --baseline-dir baselines/ \
          --current-dir screenshots/ \
          --diff-dir visual-diffs/ \
          --browser ${{ matrix.browser }}
          
    - name: Upload screenshots
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: screenshots-${{ matrix.browser }}-${{ matrix.test-suite }}
        path: screenshots/
        retention-days: 7
        
    - name: Upload visual diffs
      uses: actions/upload-artifact@v4
      if: failure() && github.event_name == 'pull_request'
      with:
        name: visual-diffs-${{ matrix.browser }}-${{ matrix.test-suite }}
        path: visual-diffs/
        retention-days: 14
        
    - name: Upload test reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-reports-${{ matrix.browser }}-${{ matrix.test-suite }}
        path: test-reports/
        retention-days: 30

  # Merge and report job
  report-results:
    needs: e2e-enhanced
    runs-on: ubuntu-latest
    if: always()
    
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      
    - name: Merge test reports
      run: |
        python scripts/merge_e2e_reports.py \
          --input-dir . \
          --output merged-e2e-report.md
          
    - name: Comment PR with results
      uses: actions/github-script@v7
      if: github.event_name == 'pull_request'
      with:
        script: |
          const fs = require('fs');
          const reportPath = 'merged-e2e-report.md';
          if (fs.existsSync(reportPath)) {
            const report = fs.readFileSync(reportPath, 'utf8');
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `## 🎭 Enhanced E2E Test Results\n\n${report}`
            });
          }
```

### Cost-Optimized Workflow
```yaml
# .github/workflows/e2e-lite.yml
name: E2E Tests (Lite Mode)

on:
  push:
    branches-ignore: [ main ]
  pull_request:
    paths:
      - 'src/**'
      - 'e2e/**'
      - 'pyproject.toml'

jobs:
  e2e-lite:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup and run lite E2E tests
      run: |
        # Visual verification only, no Claude Code API calls
        python e2e/run_visual_only_tests.py
```

### 1. Performance Optimization
- **Selective Testing**: Run full suite only on main branch
- **Changed File Detection**: Test only affected components
- **Parallel Execution**: Matrix-based browser and test suite distribution
- **Resource Management**: Optimal browser instance lifecycle

### 2. Cost Management
- **API Usage Control**: Configurable Claude Code SDK usage limits
- **Test Mode Selection**: Full/Lite/Visual-only modes
- **Branch-based Strategy**: Different test coverage by branch importance
- **Cache Optimization**: Browser binary and dependency caching

### 3. Visual Regression Management
```python
# e2e/visual_regression_check.py
class VisualRegressionChecker:
    def __init__(self, baseline_dir: str, current_dir: str):
        self.baseline_dir = baseline_dir
        self.current_dir = current_dir
        
    def compare_screenshots(self, threshold: float = 0.05):
        """Compare current screenshots with baselines"""
        pass
        
    def generate_diff_report(self):
        """Generate visual difference report"""
        pass
        
    def update_baselines(self, approved_changes: list):
        """Update baselines for approved visual changes"""
        pass
```

### Enhanced File Structure
```
.github/
└── workflows/
    ├── e2e-enhanced.yml          # Full enhanced E2E testing
    ├── e2e-lite.yml              # Cost-optimized testing
    └── update-baselines.yml      # Baseline management

e2e/
├── enhanced_display_tester.py   # Complete E2E framework
├── visual_regression_check.py   # Visual diff detection
├── ci_optimizations.py          # CI-specific optimizations
├── baseline_manager.py          # Baseline management utilities
├── baselines/                   # Reference screenshots
│   ├── chromium/
│   └── firefox/
└── scripts/
    ├── merge_e2e_reports.py     # Report consolidation
    ├── update_baselines.py      # Baseline update automation
    └── ci_health_check.py       # CI environment validation

scripts/
├── merge_e2e_reports.py         # Multi-browser report merging
└── setup_ci_environment.py      # CI environment preparation
```

### Environment Variables
```yaml
# Required secrets and variables
secrets:
  ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}

env:
  DISPLAY: :99
  CI_MODE: true
  BROWSER_TYPE: chromium|firefox
  E2E_MODE: full|lite|visual-only
  VISUAL_REGRESSION_THRESHOLD: 0.05
```

### Pull Request Testing
- **Visual Regression Check**: Compare against main branch baselines
- **Cross-browser Verification**: Ensure compatibility across browsers
- **Performance Impact Assessment**: Monitor resource usage changes
- **Report Generation**: Automated PR comments with results

### Main Branch Testing
- **Comprehensive Testing**: Full test suite with all browsers
- **Baseline Updates**: Automatic baseline refresh if tests pass
- **Performance Monitoring**: Track CI execution trends
- **Artifact Archival**: Long-term storage of test evidence

### Release Testing
- **Extended Testing**: Additional compatibility and stress testing
- **Documentation Generation**: Automated test coverage reports
- **Baseline Validation**: Ensure all baselines are current
- **Performance Benchmarking**: Comprehensive performance analysis

## Success Criteria
- [ ] GitHub Actions workflows successfully execute enhanced E2E tests
- [ ] Cross-browser testing provides consistent results across Chromium and Firefox
- [ ] Visual regression detection catches UI changes automatically
- [ ] CI execution time remains under 15 minutes for full test suite
- [ ] Cost optimization reduces API usage by 70% for non-critical branches
- [ ] Automated PR comments provide actionable test feedback
- [ ] Test artifacts are properly managed and accessible
- [ ] Visual baselines are automatically maintained and updated

## Dependencies
- ✅ Issue #231: ttyd + Playwright integration completed
- ✅ Issue #232: Full E2E test migration completed
- GitHub Actions runner environment
- Repository secrets configuration (ANTHROPIC_API_KEY)
- Visual baseline establishment

## Timeline
- **Week 1**: Basic GitHub Actions workflow setup and testing
- **Week 2**: Cross-browser matrix implementation and optimization
- **Week 3**: Visual regression detection and reporting integration
- **Week 4**: Performance optimization and cost management features
- **Week 5**: Documentation, baseline management, and final testing

## Related Issues
This is the final phase of a 3-part E2E testing enhancement:
1. ✅ **Phase 1**: ttyd + Playwright MCP integration (Issue #231)
2. ✅ **Phase 2**: Full migration of existing E2E tests (Issue #232)
3. **This Issue**: GitHub Actions CI/CD integration

### Repository Settings
```yaml
# .github/settings.yml (recommended)
repository:
  name: oboyu
  description: Enhanced search and indexing tool with visual E2E testing
  
protection_rules:
  main:
    required_status_checks:
      - Enhanced E2E Tests (ttyd + Playwright)
      - e2e-enhanced (chromium, cli)
      - e2e-enhanced (firefox, cli)
    
secrets:
  - ANTHROPIC_API_KEY  # Required for Claude Code SDK integration
```

### Cost Management
- **API Usage Monitoring**: Track Claude Code SDK usage across CI runs
- **Selective Testing**: Full tests only on main branch and releases
- **Efficient Resource Usage**: Optimize browser startup and cleanup
- **Cache Strategy**: Maximize dependency and browser binary caching

## Notes
- Full enhanced E2E testing will be enabled for main branch and releases
- Pull requests will use cost-optimized testing with visual regression detection
- Visual baselines will be automatically maintained and updated
- CI performance will be continuously monitored and optimized
- Test artifacts will be retained according to importance and storage policies
