### ISSUE TITLE
Implement missing installation testing infrastructure

### ISSUE THREAD

**Issue by sonesuke** [sonesuke/oboyu#236]
## Problem

The repository documentation extensively references installation testing infrastructure that doesn't actually exist, causing build failures and confusion. The documentation mentions:

- `.github/workflows/test-installation.yml` - Referenced in multiple docs but missing
- `Dockerfile.test` - Multi-stage testing environments (missing)
- `docker-compose.test.yml` - Test orchestration (missing) 
- `test-pip-install` job that should build wheels and populate `dist/` directory

## Current Issues

1. **Build Failures**: The `dist/` directory error (`ERROR: lstat /dist: no such file or directory`) occurs because no workflow is actually running `python -m build --wheel`
2. **Documentation Mismatch**: Extensive documentation describes testing infrastructure that doesn't exist
3. **Missing CI/CD**: No automated installation testing despite being critical for PyPI releases

## Expected Implementation

Based on the documentation, we need to create:

### 1. GitHub Actions Workflow (`.github/workflows/test-installation.yml`)
```yaml
name: Test Installation

on:
  push:
    branches: [main, develop]
  pull_request:
  release:
    types: [published, prereleased]
  schedule:
    - cron: '0 2 * * *'  # Daily at 2 AM UTC

jobs:
  test-pip-install:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.13']
        install-method: ['source', 'wheel']
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Install from source
        if: matrix.install-method == 'source'
        run: |
          python -m venv test-env
          test-env/bin/pip install -e .
          
      - name: Install from wheel
        if: matrix.install-method == 'wheel'
        run: |
          python -m venv test-env
          test-env/bin/pip install build
          test-env/bin/python -m build --wheel
          test-env/bin/pip install dist/*.whl
          
      - name: Verify installation
        run: |
          test-env/bin/python -c "import oboyu; print(oboyu.__version__)"
          test-env/bin/oboyu --help
```

### 2. Docker Test Environment (`Dockerfile.test`)
```dockerfile
FROM python:3.13-slim as base

WORKDIR /app
COPY . .

# Test pip install from source
FROM base as test-pip-source
RUN pip install .
RUN python -c "import oboyu; print('✓ Import successful')"
RUN oboyu --help

# Test pip install from wheel
FROM base as test-pip-wheel
RUN pip install build
RUN python -m build --wheel
RUN pip install dist/*.whl
RUN python -c "import oboyu; print('✓ Wheel install successful')"
RUN oboyu --help

# Test editable install
FROM base as test-pip-editable
RUN pip install -e .
RUN python -c "import oboyu; print('✓ Editable install successful')"
RUN oboyu --help
```

### 3. Docker Compose Test Orchestration (`docker-compose.test.yml`)
```yaml
version: '3.8'
services:
  test-pip-source:
    build:
      context: .
      dockerfile: Dockerfile.test
      target: test-pip-source
    environment:
      - TEST_NAME=pip-source
      
  test-pip-wheel:
    build:
      context: .
      dockerfile: Dockerfile.test
      target: test-pip-wheel
    environment:
      - TEST_NAME=pip-wheel
      
  test-pip-editable:
    build:
      context: .
      dockerfile: Dockerfile.test  
      target: test-pip-editable
    environment:
      - TEST_NAME=pip-editable
```

## Acceptance Criteria

- [ ] Create `.github/workflows/test-installation.yml` with matrix testing
- [ ] Create `Dockerfile.test` with multi-stage testing scenarios
- [ ] Create `docker-compose.test.yml` for test orchestration
- [ ] Ensure `dist/` directory is properly created and populated with wheels
- [ ] All installation methods (source, wheel, editable) work correctly
- [ ] Tests run on push, PR, release, and scheduled
- [ ] Documentation matches actual implementation
- [ ] Integration with existing `tests/test_installation_validation.py`

## Benefits

1. **Early Detection**: Catch installation issues before users encounter them
2. **Release Safety**: Prevent publishing broken packages to PyPI
3. **Platform Confidence**: Ensure compatibility across environments
4. **Documentation Accuracy**: Align docs with actual implementation

## Files to Create/Modify

- `.github/workflows/test-installation.yml` (new)
- `Dockerfile.test` (new) 
- `docker-compose.test.yml` (new)
- Update documentation to reflect actual implementation
- Integrate with existing `tests/test_installation_validation.py`

This resolves the current `dist/` directory build failures and provides the comprehensive installation testing framework described in the documentation.
