### ISSUE TITLE
Fix GitHub Actions Node.js caching error in Python project

### ISSUE THREAD

**Issue by sonesuke** [sonesuke/oboyu#237]
## Problem

The GitHub Actions workflow is failing with the error:
```
Some specified paths were not resolved, unable to cache dependencies.
```

This occurs because the workflow is configured to cache Node.js dependencies using:
```yaml
- name: Setup Node.js
  uses: actions/setup-node@v4
  with:
    node-version: '20'
    cache: 'npm'
    cache-dependency-path: website/package-lock.json
```

However, this is a **Python project** and the specified path `website/package-lock.json` does not exist in the repository.

## Root Cause

The repository analysis shows:
- This is a Python project using `pyproject.toml`
- No `website/` directory exists
- No `package.json` or `package-lock.json` files are present
- Documentation is hosted on GitHub Pages at `https://sonesuke.github.io/oboyu/`

### Option 1: Remove Node.js setup (if not needed)
If Node.js is not required for the workflow, remove the Node.js setup entirely:
```yaml
# Remove this section if Node.js is not needed
- name: Setup Node.js
  uses: actions/setup-node@v4
  with:
    node-version: '20'
    cache: 'npm'
    cache-dependency-path: website/package-lock.json
```

### Option 2: Fix Node.js caching (if needed for docs)
If Node.js is needed for documentation building, fix the caching configuration:
```yaml
- name: Setup Node.js
  uses: actions/setup-node@v4
  with:
    node-version: '20'
    cache: 'npm'
    # Remove cache-dependency-path or point to correct location
```

### Option 3: Configure Python caching instead
Since this is a Python project, consider using Python dependency caching:
```yaml
- name: Setup Python
  uses: actions/setup-python@v4
  with:
    python-version: '3.x'
    cache: 'pip'
```

## Files to Check

The issue is likely in one of these workflow files:
- `.github/workflows/test-installation.yml`
- `.github/workflows/release.yml` 
- `.github/workflows/prerelease.yml`

## Impact

This error prevents successful CI/CD pipeline execution and may block:
- Automated testing
- Documentation deployment
- Release processes
