### ISSUE TITLE
GitHub Actions Test Installation Workflow Failing - Docker Build and Dependency Issues

### ISSUE THREAD

**Issue by sonesuke** [sonesuke/oboyu#348]
## Problem Description

The GitHub Actions "Test Installation" workflow is failing with exit code 1. The workflow run https://github.com/sonesuke/oboyu/actions/runs/15670562784 shows failures in the Docker-based installation tests.

## Root Cause Analysis

After analyzing the repository structure and workflow configuration, I've identified several critical issues:

### 1. Docker Build Dependency Chain Issues
- The `test-pip-wheel` Docker stage depends on `build-wheel` service, but the wheel building process in GitHub Actions is not properly synchronized
- The workflow runs `python -m build --wheel` before Docker commands, but there's no guarantee the wheel is available when Docker tries to copy it
- Missing proper dependency ordering in the Docker Compose file

### 2. Disk Space Issues
- The Dockerfile.test installs PyTorch with CPU optimizations multiple times across different stages
- Even with `pip cache purge`, the disk usage may exceed GitHub Actions runner limits
- Multiple virtual environments are created simultaneously, consuming significant disk space

### 3. UV Installation PATH Issues
```dockerfile
# This configuration has PATH issues
RUN curl -LsSf https://astral.sh/uv/install.sh | sh
ENV PATH="/root/.local/bin:$PATH"
# Later switches to testuser but PATH may not be properly inherited
USER testuser
ENV PATH="/home/testuser/.local/bin:$PATH"
```

### 4. Missing Error Handling
- Docker stages don't have proper error handling for failed installations
- No clear indication of which specific test stage is failing

## Files Affected

- `.github/workflows/test-installation.yml` - Main workflow file
- `tests/installation/docker/Dockerfile.test` - Docker test environment
- `tests/installation/docker/docker-compose.test.yml` - Docker orchestration

### Immediate Fixes

1. **Fix Docker Build Dependencies**
```yaml
# In test-installation.yml, ensure wheel is built before Docker tests
- name: Build wheel for Docker tests
  run: |
    pip install build
    python -m build --wheel
    ls -la dist/  # Verify wheel exists

- name: Build and test Docker environments
  run: |
    # Copy wheel to Docker context first
    cp dist/*.whl tests/installation/docker/
    docker-compose -f tests/installation/docker/docker-compose.test.yml build
```

2. **Optimize Disk Usage**
```dockerfile
# Use multi-stage builds more efficiently
# Install PyTorch once in base stage, not in each test stage
FROM python:3.13-slim as base-with-torch
RUN pip install --index-url https://download.pytorch.org/whl/cpu torch && \
    pip cache purge && \
    rm -rf /root/.cache/pip
```

3. **Fix UV PATH Issues**
```dockerfile
# Install UV properly for testuser
FROM base as test-uv
USER root
RUN curl -LsSf https://astral.sh/uv/install.sh | sh
RUN cp /root/.local/bin/uv /usr/local/bin/uv
USER testuser
```

4. **Add Better Error Handling**
```dockerfile
# Add error handling in Docker stages
RUN set -e && \
    . /home/testuser/venv-source/bin/activate && \
    python -c "import oboyu; print('Source installation successful')" && \
    oboyu --help || (echo "Installation test failed" && exit 1)
```

### Long-term Improvements

1. **Simplify Test Matrix**: Start with fewer test scenarios to reduce complexity
2. **Use GitHub Actions Services**: Consider using GitHub Actions services instead of Docker Compose for database dependencies
3. **Parallel Test Execution**: Run tests in parallel with proper resource allocation
4. **Add Retry Logic**: Implement retry mechanisms for flaky installation steps

## Acceptance Criteria

- [ ] All three test jobs (`test-pip-install`, `test-docker-install`, `test-installation-validation`) pass successfully
- [ ] Docker builds complete without disk space issues
- [ ] UV installation tests work correctly
- [ ] Wheel-based installation tests function properly
- [ ] Clear error messages when tests fail

## Priority

**High** - This is blocking the daily scheduled runs and will prevent releases from working properly since installation tests are mandatory before any release.

## Labels

- `bug`
- `ci-cd`
- `installation`
- `docker`
- `github-actions`
