### ISSUE TITLE
Fix Intermittent Import Error - `src/` Not in PYTHONPATH

### ISSUE THREAD

**Issue by sonesuke** [sonesuke/oboyu#39]
## Problem

`uv run oboyu` occasionally fails with import errors, indicating that the `src/` directory is not properly included in PYTHONPATH. The error disappears after deleting `.venv` and running `uv sync`, suggesting an environment setup issue.

### Error Symptoms
```bash
$ uv run oboyu --help
ImportError: No module named 'oboyu'
# or similar import-related errors
```

### Current Workaround
```bash
# Delete virtual environment and resync
rm -rf .venv
uv sync
uv run oboyu --help  # Now works correctly
```

### Possible Causes

1. **Inconsistent Package Installation**
   - `uv sync` may not always properly install the package in development mode
   - Cached installation state might be corrupted

2. **PYTHONPATH Configuration Issues**
   - `src/` directory not consistently added to PYTHONPATH
   - Environment variable conflicts

3. **pyproject.toml Configuration**
   - Missing or incorrect development installation configuration
   - Improper source directory specification

4. **UV Environment Management**
   - Race conditions in virtual environment setup
   - Inconsistent development mode installations

### 1. Check Current pyproject.toml

Examine the current project structure:

```toml
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "oboyu"
# ... other config

# Check if this section exists and is correct
[tool.hatch.build.targets.wheel]
sources = ["src"]
```

### 2. Verify Package Structure

Expected structure:
```
oboyu/
├── src/
│   └── oboyu/
│       ├── __init__.py
│       ├── cli/
│       └── ...
├── pyproject.toml
└── uv.lock
```

### 3. Check UV Installation Method

```bash
# Check how package is currently installed
uv run python -c "import sys; print(sys.path)"
uv run python -c "import oboyu; print(oboyu.__file__)"
```

### Solution 1: Fix pyproject.toml Configuration

Ensure proper source directory configuration:

```toml
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "oboyu"
# ... existing config

# Explicitly configure source directory
[tool.hatch.build.targets.wheel]
sources = ["src"]

[tool.hatch.build.targets.sdist]
sources = ["src"]

# Ensure development installation works correctly
[tool.hatch.envs.default]
dev-mode = true
```

### Solution 2: Add Explicit Development Dependencies

```toml
[project.optional-dependencies]
dev = [
    # Development dependencies
]

# Or use uv's development group
[dependency-groups]
dev = [
    # Development dependencies
]
```

### Solution 3: Fix UV Script Configuration

Update the script configuration to be more explicit:

```toml
[project.scripts]
oboyu = "oboyu.cli.main:run"

# Or with explicit module path
[project.entry-points."console_scripts"]
oboyu = "oboyu.cli.main:run"
```

### Solution 4: Add UV-Specific Configuration

```toml
[tool.uv]
dev-dependencies = [
    # Development-specific packages
]

# Ensure consistent environment setup
[tool.uv.sources]
# Explicit source configuration if needed
```

### Solution 5: Environment Setup Script

Create a setup verification script:

```python
# scripts/verify_setup.py
#!/usr/bin/env python3
"""Verify that oboyu can be imported correctly."""

import sys
import os
from pathlib import Path

def verify_setup():
    """Verify development environment setup."""
    print("Python path:")
    for path in sys.path:
        print(f"  {path}")
    
    print(f"\nPython executable: {sys.executable}")
    
    # Check if src is in path
    repo_root = Path(__file__).parent.parent
    src_path = repo_root / "src"
    
    if str(src_path) not in sys.path:
        print(f"WARNING: {src_path} not in sys.path")
        return False
    
    # Try importing oboyu
    try:
        import oboyu
        print(f"✓ oboyu imported successfully from: {oboyu.__file__}")
        return True
    except ImportError as e:
        print(f"✗ Failed to import oboyu: {e}")
        return False

if __name__ == "__main__":
    success = verify_setup()
    sys.exit(0 if success else 1)
```

### Phase 1: Investigate Current State
- [ ] Examine current `pyproject.toml` configuration
- [ ] Document exact error conditions and frequency
- [ ] Test import behavior in clean environments

### Phase 2: Configuration Fixes
- [ ] Update `pyproject.toml` with explicit source configuration
- [ ] Add development environment verification
- [ ] Test with fresh virtual environments

### Phase 3: UV-Specific Optimizations
- [ ] Add UV-specific configuration if needed
- [ ] Create environment verification script
- [ ] Add troubleshooting documentation

### Phase 4: Testing and Validation
- [ ] Test across different systems (Linux, macOS, Windows)
- [ ] Verify behavior with different UV versions
- [ ] Add CI checks for import consistency

### Manual Testing
```bash
# Test sequence to reproduce and verify fix
rm -rf .venv
uv sync
uv run python -c "import oboyu; print('OK')"
uv run oboyu --help

# Repeat multiple times to check consistency
for i in {1..10}; do
    echo "Test run $i"
    uv run python -c "import oboyu; print('OK')" || echo "FAILED"
done
```

### Automated Testing
```yaml
# Add to CI/CD pipeline
- name: Test import consistency
  run: |
    for i in {1..5}; do
      rm -rf .venv
      uv sync
      uv run python -c "import oboyu" || exit 1
      uv run oboyu --help || exit 1
    done
```

## Success Criteria

1. ✅ `uv run oboyu` works consistently without requiring `.venv` deletion
2. ✅ Import errors eliminated completely
3. ✅ Clean virtual environment setup every time
4. ✅ Consistent behavior across different systems
5. ✅ Fast environment setup (no unnecessary reinstalls)

## Risk Assessment

**Risk Level:** Medium
- Could affect development workflow
- May impact CI/CD reliability
- Potential for environment-specific issues

**Mitigation:**
- Thorough testing across environments
- Clear rollback plan (current workaround)
- Documentation of troubleshooting steps

## Related Issues

- UV virtual environment management
- Python packaging best practices
- Development workflow reliability
