### ISSUE TITLE
Add RAG System Accuracy Evaluation for Japanese Document Search

### ISSUE THREAD

**Issue by sonesuke** [sonesuke/oboyu#46]
## Overview
Implement accuracy evaluation for Oboyu as a complete RAG (Retrieval-Augmented Generation) system, focusing on end-to-end document search and retrieval performance. This builds upon the existing speed benchmarking to provide comprehensive RAG system evaluation.

## Background
- Oboyu is a Japanese-enhanced semantic search system for local documents
- Current benchmarking focuses on speed (indexing and search)
- Need to evaluate RAG system accuracy using Japanese datasets
- Reranker implementation is planned and should be included in evaluation

## Scope
**RAG System Components to Evaluate:**
- **Retrieval**: Vector search accuracy and relevance
- **Reranking**: Post-retrieval result optimization (planned implementation)
- **End-to-end**: Complete RAG pipeline performance

**Evaluation Focus:**
- Japanese document search accuracy
- Query-document relevance matching
- Multi-hop information retrieval
- Real-world RAG use case scenarios

#### Infrastructure Setup
- [ ] Create `bench/rag_accuracy/` directory structure
- [ ] Implement RAG evaluation framework
- [ ] Set up Japanese dataset management system

#### Directory Structure
```
bench/
├── rag_accuracy/
│   ├── __init__.py
│   ├── rag_evaluator.py       # Main RAG system evaluation
│   ├── dataset_manager.py     # Japanese dataset management
│   ├── metrics_calculator.py  # RAG-specific metrics
│   ├── reranker_evaluator.py  # Reranking evaluation (for planned feature)
│   └── results_analyzer.py    # Result analysis and reporting
├── benchmark_rag_accuracy.py  # Main RAG accuracy benchmark script
└── config/
    └── rag_eval_config.yaml   # RAG evaluation configuration
```

#### Primary Datasets (JMTEB Retrieval Tasks)
- [ ] **MIRACL-ja** - Multilingual information retrieval (Japanese split)
- [ ] **MLDR-ja** - Long document retrieval (Japanese split)
- [ ] **JaGovFaqs-22k** - Japanese government FAQ retrieval
- [ ] **JaCWIR** - Japanese casual web information retrieval

#### Additional RAG-Focused Datasets
- [ ] **Custom Japanese Q&A datasets** - Tailored for RAG evaluation
- [ ] **Multi-hop reasoning datasets** - Complex information synthesis
- [ ] **Domain-specific datasets** - Technical documentation, manuals

#### Retrieval Component
- [ ] **Vector Search Accuracy**: Precision@K, Recall@K, NDCG@K
- [ ] **Query-Document Matching**: Semantic relevance scoring
- [ ] **Multi-language Support**: Japanese/English mixed content
- [ ] **Context Window Performance**: Long document handling

#### Reranking Component (Planned Feature)
- [ ] **Re-ranking Effectiveness**: Improvement over initial retrieval
- [ ] **Ranking Quality**: MRR (Mean Reciprocal Rank), MAP (Mean Average Precision)
- [ ] **Latency vs. Accuracy Trade-offs**: Performance optimization
- [ ] **Japanese Language Optimization**: Language-specific ranking improvements

#### End-to-End RAG Performance
- [ ] **Complete Pipeline Evaluation**: Indexing → Retrieval → Reranking
- [ ] **Real-world Scenarios**: Typical user query patterns
- [ ] **Scalability Assessment**: Performance across different corpus sizes

#### RAG-Specific Metrics
- [ ] **Retrieval Metrics**:
  - Precision@K, Recall@K (K = 1, 5, 10, 20)
  - NDCG@K (Normalized Discounted Cumulative Gain)
  - MRR (Mean Reciprocal Rank)
  - Hit Rate (% queries with at least one relevant result)

- [ ] **Reranking Metrics**:
  - Ranking improvement over baseline retrieval
  - Position-based effectiveness measurement
  - Query response time impact

- [ ] **System-Level Metrics**:
  - End-to-end accuracy across different query types
  - Japanese language processing effectiveness
  - Multi-hop reasoning capability

#### Comprehensive Analysis
- [ ] **Performance Profiling**: Component-wise accuracy breakdown
- [ ] **Error Analysis**: Common failure patterns and causes
- [ ] **Comparative Analysis**: Performance across different Japanese datasets
- [ ] **Speed vs. Accuracy Correlation**: Integration with existing speed benchmarks

### Dependencies
```yaml
# Additional dependencies for RAG accuracy evaluation
datasets: ">=2.0.0"
numpy: ">=1.21.0"
scipy: ">=1.7.0"
scikit-learn: ">=1.0.0"
pandas: ">=1.3.0"
```

### Configuration
```yaml
# rag_eval_config.yaml
rag_evaluation:
  datasets:
    retrieval:
      - "miracl-ja"
      - "mldr-ja"
      - "jagovfaqs-22k"
      - "jacwir"
    
  metrics:
    retrieval:
      - "precision_at_k"
      - "recall_at_k"
      - "ndcg_at_k"
      - "mrr"
      - "hit_rate"
    reranking:
      - "ranking_improvement"
      - "map"
      - "reranking_effectiveness"
    
  evaluation_params:
    top_k_values: [1, 5, 10, 20]
    batch_size: 32
    test_size: 1000  # Number of queries to evaluate per dataset
```

### Phase 1-2 Complete
- [ ] RAG evaluation framework operational
- [ ] Japanese datasets successfully integrated
- [ ] Basic retrieval accuracy metrics working

### Phase 3-4 Complete
- [ ] Complete RAG pipeline evaluation functional
- [ ] Reranking evaluation ready for implementation
- [ ] Comprehensive accuracy reports generated
- [ ] Performance baselines established for future optimization

### Immediate Benefits
- **RAG System Validation**: Confirm Oboyu's effectiveness as a Japanese RAG system
- **Component Performance**: Identify strengths/weaknesses in retrieval pipeline
- **Benchmark Establishment**: Create baselines for future improvements

### Long-term Benefits
- **Optimization Roadmap**: Data-driven improvement priorities
- **Feature Development**: Guide reranker implementation and tuning
- **Quality Assurance**: Prevent accuracy regressions during development
- **Competitive Positioning**: Establish Oboyu's performance in Japanese RAG space

### Speed + Accuracy Correlation
- [ ] Combine with existing speed benchmarks
- [ ] Analyze speed vs. accuracy trade-offs
- [ ] Optimize for different use case requirements

### Continuous Evaluation
- [ ] Integrate with development workflow
- [ ] Automated accuracy regression detection
- [ ] Performance trend tracking over time

## Notes
- Focus on RAG system evaluation, not individual embedding model performance
- Include reranker evaluation framework for planned implementation
- Emphasize Japanese language capabilities and real-world use cases
- Build upon existing speed benchmarking infrastructure
- Prepare for future enhancements (hybrid search, advanced reranking)

## Dependencies
- Requires completion of speed benchmarking infrastructure
- Access to Japanese RAG evaluation datasets
- Sufficient computational resources for comprehensive evaluation
