### ISSUE TITLE
Adjust default chunk size to fit within reranker model constraints to eliminate truncation warnings

### ISSUE THREAD

**Issue by sonesuke** [sonesuke/oboyu#89]
Users experience repeated tokenizer truncation warnings when using the reranker feature:

```
Be aware, overflowing tokens are not returned for the setting you have chosen, i.e. sequence pairs with the 'longest_first' 
truncation strategy. So the returned list will always be empty even if some tokens have been removed.
```

This warning appears multiple times during `oboyu query --interactive --rerank` sessions, indicating that the current chunk size configuration is incompatible with the reranker model's sequence length limitations.

## Problem Analysis

**Current Configuration:**
- Default chunk size: 1024 characters
- Reranker models: `cl-nagoya/ruri-reranker-small` (default) and `cl-nagoya/ruri-v3-reranker-310m`
- Reranker max sequence length: 512 tokens
- Current reranker input format: `query + [SEP] + document_chunk`

**Issue:**
The total token count often exceeds 512 tokens, especially with:
- Japanese text (where 1 character ≈ 1 token)
- Longer queries (検索クエリ prefix + user query)
- Document chunks (検索文書 prefix + chunk content)

## Root Cause

The chunk size was optimized for embedding models (ruri-v3-30m with 8192 max tokens) but not for reranker models (512 max tokens). This mismatch causes:

1. **Information Loss**: Truncated content is not considered in reranking
2. **Poor User Experience**: Repeated warnings during interactive sessions  
3. **Suboptimal Reranking**: Incomplete text affects relevance scoring accuracy

## Proposed Solution

**Adjust default chunk size to fit within reranker constraints:**

```yaml
indexer:
  chunk_size: 300          # Reduced from 1024 to fit reranker limits
  chunk_overlap: 75        # Reduced proportionally (25% of chunk_size)
  reranker_max_length: 512 # Document the actual constraint
```

**Calculation Logic:**
```
Total available tokens: 512
- Query prefix tokens: ~10 ("検索クエリ: ")
- Document prefix tokens: ~10 ("検索文書: ") 
- Separator tokens: ~5 ([SEP], [CLS], etc.)
- Safety margin: ~50
- Average user query: ~50 tokens
= Available for document chunk: ~387 tokens
→ Conservative chunk size: 300 characters
```

### 1. **Update Default Configuration**

**Before:**
```python
DEFAULT_CONFIG = {
    "indexer": {
        "chunk_size": 1024,
        "chunk_overlap": 256,
        # ...
    }
}
```

**After:**
```python
DEFAULT_CONFIG = {
    "indexer": {
        "chunk_size": 300,  # Optimized for reranker compatibility
        "chunk_overlap": 75, # Maintain 25% overlap ratio
        "reranker_max_length": 512,
        # ...
    }
}
```

### 2. **Add Validation**

```python
def validate_chunk_size_for_reranker(chunk_size: int, reranker_max_length: int) -> None:
    """Validate that chunk size is compatible with reranker constraints."""
    max_recommended = reranker_max_length * 0.6  # Conservative estimate
    if chunk_size > max_recommended:
        logger.warning(
            f"Chunk size ({chunk_size}) may exceed reranker capacity "
            f"(recommended: <{max_recommended}). Consider reducing chunk_size."
        )
```

### 3. **Documentation Updates**

Update configuration documentation to explain the relationship between chunk size and reranker performance:

```yaml
indexer:
  # Chunk size optimized for reranker models (max 512 tokens)
  # Larger sizes may cause truncation warnings and degraded reranking
  chunk_size: 300
  
  # For embedding-only usage, larger chunks can be used:
  # chunk_size: 1024  # Suitable when reranker is disabled
```

### For New Users
- New installations will use optimized defaults
- No action required

### For Existing Users
- **Breaking Change**: Existing indexes may need re-indexing for optimal reranker performance
- **Migration Path**: 
  1. Provide clear upgrade instructions
  2. Add configuration option to maintain legacy chunk sizes
  3. Recommend re-indexing for users who use reranker frequently

### Backward Compatibility Option
```yaml
indexer:
  chunk_size: 1024  # Legacy size for embedding-optimized indexes
  reranker_chunk_override: 300  # Use smaller chunks only for reranking
```

## Benefits

1. **Eliminates Warnings**: No more tokenizer truncation warnings
2. **Improves Reranking Quality**: Complete text content considered
3. **Better User Experience**: Clean interactive sessions
4. **Optimal Performance**: Chunk size aligned with model capabilities

## Performance Impact

- **Positive**: Better reranking accuracy, no truncation
- **Consideration**: Smaller chunks may increase total chunk count by ~3x
- **Mitigation**: Modern systems can handle the additional chunks efficiently

## Testing Plan

1. **Functional Testing**:
   - Verify no truncation warnings with new chunk size
   - Test reranking quality with Japanese and English content
   
2. **Performance Testing**:
   - Measure indexing time with increased chunk count
   - Verify search performance remains acceptable
   
3. **Integration Testing**:
   - Test with both reranker models
   - Verify interactive mode works smoothly

---

This change aligns the system architecture with the actual capabilities of the reranker models, eliminating user-facing warnings while improving search quality.
