### ISSUE TITLE
Add pylint C0302 (too-many-lines) check to complement Ruff linting

### ISSUE THREAD

**Issue by sonesuke** [sonesuke/oboyu#94]
## Overview
Add pylint's `C0302` (too-many-lines) check to the project's linting setup while keeping Ruff for all other code quality checks. This will help maintain code maintainability by enforcing file length limits.

### 1. Pylint Configuration
- Add pylint to the project dependencies
- Configure pylint in `pyproject.toml` to **only** enable the `C0302` check
- Disable all other pylint checks since we use Ruff for those
- Set appropriate line limit threshold (suggest 1000 lines as starting point)

### 2. Pre-commit Integration
- Add pylint hook to `.pre-commit-config.yaml`
- Ensure it runs alongside existing Ruff checks
- Configure to only check Python files

### 3. Configuration Details
Expected `pyproject.toml` configuration:
```toml
[tool.pylint]
disable = "all"
enable = "line-too-long"  # C0302
max-line-length = 1000
```

Expected `.pre-commit-config.yaml` addition:
```yaml
- repo: local
  hooks:
    - id: pylint-line-length
      name: pylint line length check
      entry: pylint
      language: system
      types: [python]
      args: ["--disable=all", "--enable=line-too-long"]
```

## Benefits
- Encourages breaking down large files into smaller, more maintainable modules
- Complements Ruff's fast linting with specific line count enforcement
- Maintains consistency with existing pyproject.toml configuration approach
- Integrates seamlessly with current pre-commit workflow

## Files to Modify
- `pyproject.toml` - Add pylint configuration section
- `.pre-commit-config.yaml` - Add pylint hook
- Consider adding pylint to dev dependencies if not already present

## Acceptance Criteria
- [ ] Pylint is configured to only check C0302 (too-many-lines)
- [ ] All other pylint checks are disabled (Ruff handles them)
- [ ] Configuration is managed in pyproject.toml
- [ ] Pre-commit hook is set up and working
- [ ] Documentation is updated if necessary

## Current State Analysis
Based on the codebase analysis, several files currently exceed reasonable line limits:
- `src/oboyu/indexer/indexer.py`: ~4,671 tokens (very long)
- `src/oboyu/indexer/config_legacy.py`: ~4,215 tokens (very long)
- `src/oboyu/indexer/database.py`: ~3,787 tokens (long)

These files would benefit from refactoring into smaller, more focused modules.
